### ISSUE TITLE
[idea] police shop

### ISSUE THREAD

**Issue by ghost** [fokkonaut/F-Client#13]
add buyable jetpack endlesshook etc.
- portal rentable with money for 10 mins
make a police shop
and police shop with items meantioned before
in the police shop make possible to buy police rank
- deposit everyones money every 1 hour or something

**Comment by frutijitsu** [comment]
buyable bonuses gotta destroy all the balance (ah yes balance is already gone) autodeposit is bad, if it should be added, a mechanic with dropable money won't make sense anymore
free portal? it's already used by 2many players, it need to be nerfed (how about to place some antiportal tiles to the map?)
