### ISSUE TITLE
gamer client's auto record feature

### ISSUE THREAD

**Issue by jxsl13** [fokkonaut/F-Client#4]
gamer client's auto record feature.
Basically records when you join the server automatically until you leave, for every server.
because Tezcan does not wanna use any other client.

**Comment by jxsl13** [comment]
Tezcan is evil and might have tricked me.

**Comment by fokkonaut** [comment]
`cl_auto_demo_max 0` for unlimited auto demos and `cl_auto_demo_record 1` to enable auto recording, i use it all the time
